### ISSUE TITLE
Fix compilation with c++11 (default for gcc>=6)

### ISSUE THREAD

**Issue by vbraun** [BRiAl/BRiAl#11]
- There should be a brial testsuite that exhibits the issue
- The segfault is possibly(?) due to the different code path with hash maps

**Comment by kiwifb** [comment]
So it is only used in `libbrial/include/polybori/routines/pbori_func.h` and the relevant code would have to be

```
template <class Type, typename Comparator>
class generate_index_map {

  typedef typename Type::idx_type idx_type;
public:
  /// Type for index maps

#ifdef PBORI_HAVE_TR1_UNORDERED_MAP
  typedef std::tr1::unordered_map<Type, idx_type, hashes<Type> > type;
#else
#  ifdef PBORI_HAVE_UNORDERED_MAP
     typedef std::unordered_map<Type, idx_type, hashes<Type> > type;
#  else
#    ifdef PBORI_HAVE_HASH_MAP
       typedef __gnu_cxx::hash_map<Type, idx_type, hashes<Type> > type;
#    else
       typedef std::map<Type, idx_type, Comparator> type;
#    endif
#  endif
#endif
};
```

There is a fall back that presumably works if we remove the test for hash maps altogether.

**Comment by kiwifb** [comment]
After doing some reading I think it would be best to keep only `std::unordered_map` if it is available.

**Comment by kiwifb** [comment]
And polybori currently wouldn't use unordered maps if it was found because of a typo in the macro name between `configure.ac` (`UNORDERD_MAP`) and `libbrial/include/polybori/routines/pbori_func.h` (`UNORDERED_MAP`).

**Comment by tobihan** [comment]
Thanks for working on this. I tried the new commit 63f747626822f5e0fa2bf975f7801fcc988eb530 on i386 Debian.

It breaks two tests, namely

    unknown location(0): fatal error: in "GroebnerStrategyTestSuite/test_nf": memory access violation at address: 0x4dbd63b0: no mapping at fault address
    testsuite/src/GroebnerStrategyTest.cc(50): last checkpoint

and

    unknown location(0): fatal error: in "FGLMStrategyTest/test_constructors": memory access violation at address: 0xb133683c: no mapping at fault address
    testsuite/src/FGLMStrategyTest.cc(52): last checkpoint: "test_constructors" entry.

Also it does not fix the segmentation faults of brial within sage, that can be triggered for example by running this in sage:

    from brial import groebner_basis
    from brial.blocks import declare_ring
    r = declare_ring(['x', 'y'], globals())
    id = [x + y]
    groebner_basis(id)

All of this is true regardless of whether CXXFLAGS=-std=c++98 is set or not.

**Comment by kiwifb** [comment]
Can you check if `PBORI_HAVE_UNORDERED_MAP` is set in either case (with and without `-std=c++98`)? Should be in `libbrial/include/polybori/config.h` if I am not mistaken.

**Comment by tobihan** [comment]
Looking at this config.h file was a very good idea. Turns out that during the library build there is

    #define PBORI_HAVE_UNORDERED_MAP /**/

After that the testsuite is built, which invokes scons (see issue #12). This regenerates config.h which looks quite different and contains

    #ifndef PBORI_HAVE_TR1_UNORDERED_MAP
    #define PBORI_HAVE_TR1_UNORDERED_MAP 

This version of the file is installed. For now I disabled the tests completely to avoid this happening.

Now the config.h has with -std=c++98 flag:

    /* has unordered map */
    /* #undef PBORI_HAVE_UNORDERED_MAP */

and without the flag:

    /* has unordered map */
    #define PBORI_HAVE_UNORDERED_MAP /**/

In both cases the example above in sage still segfaults.

**Comment by tobihan** [comment]
Do I have to rebuild sage as well?

**Comment by kiwifb** [comment]
It shouldn't be necessary. Then again there could be something I don't understand in the polybori interface but from the point of view of the `.so` we shouldn't have changed anything to the API or ABI - check that, if you switch from c++98 to c++11 you should rebuild.

**Comment by kiwifb** [comment]
I also suddenly think that when compiling sage, if you use c++98 may be `-std=c++98` while building `sage/rings/polynomial/pbori.pyx` and possibly while building `sage/libs/polybori/` stuff.

**Comment by tobihan** [comment]
But sage builds brial with -std=c++98 too so it should be set up to work with that.

**Comment by kiwifb** [comment]
I think we may just be lucky. I see nothing to enforce c++98 for polybori bits inside the sage library.

**Comment by kiwifb** [comment]
I also thought I could fix `SConstruct` for the tests but I have already removed it from master. The tests really need to be migrated to autoconf.

**Comment by kiwifb** [comment]
Going back to the test again. I think you get tr1 unordered_map because c++98 is enforced in `SConstruct`. You would have to remove the flag on line 307 and 316 of `SConstruct`.

**Comment by tobihan** [comment]
Ok, using no -std=c++98 and then rebuilding sage, the segfaults are gone. The brial testsuite also works with your fix.

With -std=c++98 and then rebuilding sage, the segfaults are still there, so that would probably require some -std=c++98 flags for sage. I guess we will go with the first option.

Thanks for the help!

**Comment by tobihan** [comment]
On the other hand breaking the ABI of brial right now would be really annoying and would probably break sagemath in Debian testing for some time (when the new brial is in testing and sagemath not yet). Do you know how I can set -std=c++98 for certain parts of sagemath?

**Comment by kiwifb** [comment]
Yes, by setting distutils instructions in .pxd files. In this case I think adding
```
# distutils: extra_compile_args = -std=c++98
```
in line 2 of `sage/libs/polybori/decl.pxd` should be sufficient and it should be inherited by anything using polybori.

**Comment by kiwifb** [comment]
I hope this is all laid to rest by 0.8.7. The original failure was I believe caused by a typo in one of the files. The release incorporate fixes and rework the configuration beyond that. 

As it turns out standard C++ map is not sufficient for sage. You have to have some kind of unordered_map. The current release focuses on that. The `-std=c++98` in `spkg-install` may be harmful in the long term. I am guessing it is only useful if the compiler doesn't default to at least that standard, but it may cause problems once compiler defaulting to C++11 become prevalent. Then the sage extension may be in trouble at build time.

test suite needs to be rewritten for autoconf. No ETA at this stage.
