### ISSUE TITLE
building with gcc 6.1 apparently fails

### ISSUE THREAD

**Issue by dimpase** [BRiAl/BRiAl#8]
There is a thread on sage-release on this, see [here](https://groups.google.com/d/msg/sage-release/h-Sk_2q8YSg/0wI6cQKOAwAJ).

**Comment by antonio-rojas** [comment]
Reposting from the sage-release thread:

This seems to be the problem:
 checking unordered_map usability... no
 checking unordered_map presence... yes
 configure: WARNING: unordered_map: present but cannot be compiled
 configure: WARNING: unordered_map:     check for missing prerequisite headers?
 configure: WARNING: unordered_map: see the Autoconf documentation
 configure: WARNING: unordered_map:     section "Present But Cannot Be Compiled"
 configure: WARNING: unordered_map: proceeding with the compiler's result

The configure script tests for C++11's unordered_map, which succeeds if using GCC 6. Then it tries to use it later, which of course fails because brial enforces C++98. By exporting -std=gnu++98 before running configure, the test fails so it falls back to boost's unordered_map, and the builds finishes correctly.

**Comment by vbraun** [comment]
There is probably two issues, it should probably use c++11 std::unordered_map. But the more pressing issue is that the std::map fallback is broken.
